[project]
name = "daemon"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "google-genai>=2.23.0",
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
    "python-telegram-bot>=22.8",
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
    "trafilatura>=2.0.0",
]
